### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by ahendy0**

### CODE REVIEW

**Comment by ben-cunningham** [comment]
Isn't this redundant with our example file? I was thinking some docs like:

Facebook messages are either templates or text. To construct them, simply use 
```python
# Message(<type>, payload)
Message('text', payload)  # where payload is a string
Message('template', payload) # where payload is a Template
```

and to send a message, use 
```
bot.send_message(msg, <recipient_id>)
```

**Comment by ahendy0** [comment]
@ben-cunningham 

I've changed this to just a "quick usage" rather than a document ora  full usable file.

**Comment by ben-cunningham** [comment]
Swag. could we separate to be like
```
# Send a Generic template
web_button = Button(
    type='web_url',
    title='My Button Image',
    payload='http://www.newton.ac.uk/files/covers/968361.jpg'
)

postback_button = Button(
    type='postback',
    title='My Postback',
    payload="<USER DEFINED PAYLOAD>",
)

element = Element(
    title='Generic Template Element Title',
    subtitle='My subtitle',
    image_url='http://www.buffettworld.com/images/news_trump.jpg',
    buttons=[
        web_button,
    ]
)

generic_template = Template(
    Template.generic_type,
    elements=[
        element,                    
    ]
)

msg2 = Message('template', generic_template)
response, error = bot.send_message(msg2, recipient)
```
Send a button template
```
button_template = Template(
    Template.button_type,
    title="My Button template title",
    buttons=[
        web_button, postback_button
    ]
)

msg = Message('template', button_template)
response, error = bot.send_message(msg, recipient)
```

**Comment by ben-cunningham** [comment]
teh thoughts?

**Comment by ahendy0** [comment]
i think its pretty clear but if you want to

**Comment by ben-cunningham** [comment]
fix it later #techdebt

**Pull request merged**
